# Generated by Django 2.1.7 on 2019-02-23 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainants',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('occupation', models.CharField(choices=[('Uber Motorist', 'Uber Motorist'), ('Motor Cyclist', 'Motor Cyclist')], default='Uber Motorist', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('practise_number', models.CharField(max_length=15)),
                ('building_address', models.CharField(max_length=15)),
                ('street_road', models.CharField(max_length=15)),
                ('building_floor', models.CharField(max_length=15)),
            ],
        ),
    ]
