# Generated by Django 2.1.7 on 2019-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='status',
            field=models.BooleanField(default=False, help_text='Designates whether the user is available or not.'),
        ),
    ]
