# Generated by Django 2.1.7 on 2019-02-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0002_auto_20190223_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('offense_type', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fine', models.IntegerField()),
            ],
        ),
    ]
