# Generated by Django 2.1.7 on 2019-02-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0002_lawyer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainants',
            name='id_number',
            field=models.CharField(default=12345, max_length=15, verbose_name='id_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainants',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='id_number',
            field=models.CharField(default='12345', max_length=15, verbose_name='id_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
