# Generated by Django 2.1.7 on 2019-02-24 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0003_auto_20190224_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='offense_type',
        ),
        migrations.AddField(
            model_name='offence',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_modified'),
        ),
        migrations.AlterField(
            model_name='offence',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='offence',
            name='description',
            field=models.TextField(verbose_name='offence_description'),
        ),
        migrations.AlterField(
            model_name='offence',
            name='fine',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
