# Generated by Django 2.1.7 on 2019-02-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0004_auto_20190224_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_modified'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=False, help_text='Designates whether the complaint has been taken.'),
        ),
        migrations.AlterField(
            model_name='complainants',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complainant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
