# Generated by Django 2.1.7 on 2019-02-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0005_auto_20190224_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodajusticeapp.Complaint'),
        ),
        migrations.AddField(
            model_name='case',
            name='offence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodajusticeapp.Offence'),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='bodajusticeapp.Lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
