# Generated by Django 2.1.7 on 2019-02-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0007_auto_20190224_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodajusticeapp.Lawyer')),
            ],
        ),
        migrations.AlterField(
            model_name='policestation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='police_station'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='street_road',
            field=models.CharField(max_length=50, verbose_name='street_or_road'),
        ),
    ]
