# Generated by Django 2.1.7 on 2019-02-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodajusticeapp', '0008_auto_20190224_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='case',
            new_name='lawyer',
        ),
    ]
